config/routes.rb
Rails.application.routes.draw do

  resources :user_remark_ratings
  resources :remarks
  get 'comments/create'
  get 'comments/destroy'
  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tags
    resources :categories do
      resources :products do
        resources :remarks, only: [:create, :destroy]
      end
    end

    resources :products do
      resources :variants
    end

  resources :remarks do
    resources :user_remark_ratings
  end

    root 'categories#index'

    get '/products', to: 'products#index'
    get '/profiles', to:'products#profile'
  post '/products/:id/mark', to:'products#mark'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, length: { maximum: 20 }, presence: true
  belongs_to :category
  has_many :variants, dependent: :destroy
  has_many :remarks, dependent: :destroy

  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, reject_if: :all_blank

  belongs_to :user

  has_many :ratings, dependent: :destroy

  has_one_attached :image

  has_and_belongs_to_many :users, join_table: "products_users"
  default_scope { }


  def self.product_date(from_date,to_date)
    if from_date.present? && to_date.present?
      where("created_at between ? and ?",from_date,to_date)
    elsif from_date.nil? && to_date.nil?
      earliest_date = self.order(:created_at).pluck(:created_at).first
      latest_date = self.order(created_at: :desc).pluck(:created_at).first
      where("created_at between ? and ?", earliest_date, latest_date)
    end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[ show new edit create destroy]
  before_action :set_product, only: %i[ show edit destroy ]

  def mark
    @product = Product.find(params[:id])
    current_user.products << @product
    head :ok
  end

  # GET /products or /products.json
  def index
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @product = @category.products.includes(:variants,:ratings,:tags).product_date(params[:from_date],params[:to_date]).paginate(page: params[:page], per_page: 10)
      @name = "#{@category.name} Products"
    else
      @product = Product.includes(:category,:variants,:ratings,:tags).paginate(page: params[:page], per_page: 10)
      @name = "All Products"
    end
  end


  def profile
  end

  # GET /products/1 or /products/1.json
  def show
    @remark = @product.remarks.new
  end

  # GET /products/new
  def new
    @product = @category.products.new
    @rating = Rating.new
  end

  # GET /products/1/edit
  def edit
    @rating = Rating.new
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if params[:product][:image].present?
      @product.image.attach(params[:product][:image])
    end
    respond_to do |format|
      if @product.save
        format.js { }
        format.html { redirect_to category_product_url(@category,@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }

      else
        format.js { }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
      if params[:product][:rating].present?
        @product = Product.find(params[:id])
        @rating = @product.ratings.new(params[:product][:rating][0])
        @rating.value = params[:product][:rating][:value].to_i
        if @rating.save
          redirect_to category_products_path(@product.category_id,@product)
        end

      else
        @category = Category.find(params[:category_id])
        @product = @category.products.find(params[:id])
        if params[:product][:image].present?
          @product.image.attach(params[:product][:image])
        end
        if @product.update(product_params)
          redirect_to category_product_url(@category,@product), notice: "Product was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
      end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to category_products_url(@category), notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = @category.products.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id,:image, tags_attributes: [:name], tag_ids:[])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: [@category, product],local:false) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.fields_for :tags, @product.tags.build do |tag|  %>
    <%= tag.label 'New Tag' %>
      <%= tag.text_field :name %>
    <% end %>
  </div><br>

  <div>
    <% if Tag.any? %>
    <%= form.label 'Choose Tag' %>
      <%= form.select :tag_ids,Tag.all.collect{ |tag| [tag.name,tag.id]}, { include_blank: true } , multiple: true %>
    <% end %>
  </div><br>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/create.js.erb
<% if @product.errors.any? %>
alert("<%= @product.errors.full_messages.join(',') %>");
<% else %>
alert("product created successfully");

const url= "/categories/<%= @product.category.id %>/products/<%= @product.id%>"
history.pushState({}, '', url);
var xhr = new XMLHttpRequest();
xhr.open('GET', url);
xhr.onload = function() {
    document.documentElement.innerHTML = xhr.responseText;
};
xhr.send();
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1><br>

<%= render 'form', product: @product %>

<%= link_to 'Show', category_product_path(@category, @product) %> |
<%= link_to 'Back', category_products_path(@category) %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p><br><br>

<h1><%= @name %></h1><br>
<% if @name != "All Posts" %>
  <div>
    <%= form_tag category_products_path, method: :get do %>
      <%= label_tag :from_date, "From:",:style => "display: inline-block;" %>
      <%= date_field_tag :from_date %>
      <%= label_tag :to_date, "To:",:style => "display: inline-block;" %>
      <%= date_field_tag :to_date %>
      <%= submit_tag "Filter" %>
    <% end %>
  </div>
  <% end %>
<table style="border-spacing: 10px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>Status</th>
      <th>Tag</th>
      <th>Rating</th>
      <th>Average Rating</th>
      <th>Variants</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @product.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td style="text-align: center"><%= product.category.id %></td>
        <td>
          <% if product.users.include?(current_user) %>
          Read
          <% else %>
          UnRead
          <% end %>
        </td>
        <td>
          <% if product.tags.any? %>
            <% product.tags.each do |tag| %>
              <%= tag.name %> ,
            <% end %>
          <% else %>
            No Tag Available!
          <% end %>
        </td>
        <td>
          <% if product.ratings.any? %>
            <% product.ratings.group(:value).count.each do |i| %>
              <b><%= i[0] %></b> ⭐ given by <b><%= i[1] %></b> |
            <% end %>
          <% else %>
            No Rating Available!
          <% end %>
        </td>
        <td><%=  product.ratings_count.truncate(1) if product.ratings_count.present? %></td>
        <td>
          <% if product.variants_count.present? %>
          <div style="text-align: center"><%= product.variants_count %></div>
          <% end %>
        </td>
        <td><%= link_to 'Show', category_product_path(product.category.id, product) %></td>
        <td><%= link_to 'Edit', edit_category_product_path(product.category.id, product) %></td>
        <td><%= link_to 'Destroy', category_product_path(product.category.id, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Variants', product_variants_path(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table><br>

<% if @name != "All Products" %>
  <%= will_paginate @product %><br>
  <%= link_to 'New Product', new_category_product_path(@category) %> |
  <% else %>
  <%= will_paginate @product %><br>
<% end %>
<%= link_to 'Back Category', categories_path %>

app/views/products/new.html.erb
<h1>New Product</h1><br>

<%= render 'form', product: @product %>
<div id="load" style="display: none">
  Waiting...</div>
<%= link_to 'Back', category_products_path(@category) %>

<script>
    $("form").on('submit', function() {
        $("#load").show();
        $.ajax({
            url: $(this).attr('action'),
            type: $(this).attr('method'),
            data: $(this).serialize(),
            success: function(response) {
                $("#load").hide();
            },
            error: function(response) {
                $("#load").hide();
            }
        });
        return false;
    });</script>

app/views/products/profile.html.erb
<h1>User Profile</h1>
<br><hr>

<br>
<b>E-mail: </b>
<%= current_user.email %><br><br>
<b>Image: </b><br>
<% if current_user.avatar.attached? %><br>
  <%= image_tag current_user.avatar %>
<% else %>
  No Image Available!!
<% end %><br><br>

<%= link_to 'Edit', edit_user_registration_path %> |
<%= link_to 'Log Out', destroy_user_session_path, method: :delete %> |
<%= link_to 'Back', :back %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.id %>
</p>

<p><b>Tags:</b>
  <% if Tag.count > 0 %>
    <% if @product.tags.present? %>
      <% @product.tags.each do |tag| %>
      <li><%= tag.name %></li>
    <% end %>
  <% else %>
    No Tags Available!!
    <% end %>
    <% end %>
</p>

<p>
  <b>Ratings: </b>
  <% if @product.ratings.any? %>
  <% @product.ratings.group(:value).count.each do |i| %>
      <b><%= i[0] %></b> ⭐ given by <b><%= i[1] %></b> |
    <% end %>
  <% else %>
  No Rating Available!
  <% end %>
</p>

<p><b>Image:</b>
  <% if @product.image.attached? %><br><br>
    <%= image_tag @product.image %>
    <% else %>
  No Image Available!!
  <% end %>
</p>

<p><b>Author Name:</b>
  <% if @product.user %>
    <%= @product.user.email %>
  <% else %>
  -
<% end %>
</p>
<br>
<div>
  <p><b>Add a remark</b></p>

  <%= form_with model: [@category,@product,@remark] do |f| %>
    <%= f.text_field :body %>
    <%= f.submit %>
  <% end %>
</div>
<br>
<% if @product.remarks.count > 0 %>
  <table>
    <tbody>
    <% @product.remarks.each do |remark| %>
      <% if remark.body != nil %>
        <tr><b>Remarks: </b><br><br>
          <td><%= remark.body %> - </td>

          <td><% if remark.user_remark_ratings.any? %>
              <% remark.user_remark_ratings.group(:rate).count.each do |i| %>
                <b><%= i[0] %></b> ⭐ given by <b><%= i[1] %></b> |
              <% end %>
            <% else %>
              No Rating Available!
            <% end %> - </td>

          <td><%= render 'user_remark_ratings/form', user_remark_rating:[remark,remark.user_remark_ratings.new] %></td>
          <td><%= link_to "Destroy", category_product_remark_path(@category,@product,remark), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
<% end %><br>

<div>
  <% unless @product.users.include?(current_user) %>
  <script>
    $(document).ready(function (){
        let id = <%= @product.id %>;
        $.ajaxSetup({
           headers:{
               'X-CSRF-Token':$('meta[name="csrf-token"]').attr('content')
           }
        });
        $.ajax({
           url:'/products/'+id+'/mark',
            type:'POST'
        });
    });
  </script>
  <% end %>
</div>

<%= link_to 'Variants', product_variants_path(@product) %> |
<%= link_to 'Edit', edit_category_product_path(@category, @product) %> |
<%= link_to 'Back', category_products_path(@category) %>
<br><br><br>

<p>
<h1>Star Ratings</h1>
  <%= form_with(model:@product) do |form| %>
  <% form.fields_for :rating do |f| %>
    <div>
      <%= f.radio_button :value, 1 %>1⭐
      <%= f.radio_button :value, 2 %>2⭐
      <%= f.radio_button :value, 3 %>3⭐
      <%= f.radio_button :value, 4 %>4⭐
      <%= f.radio_button :value, 5 %>5⭐
    </div><br>
    <%= f.submit 'Submit' %>
    <% end %>
  <% end %>
</p>

<br><br>
<h1>Variants</h1>

    <% if @product.variants.length > 0 %>
      <table style="border-spacing: 10px">
        <thead>
        <tr>
          <th>Colour</th>
          <th>Price</th>
          <th>Author Name</th>
          <th>Product ID</th>
          <th colspan="3">Action</th>
        </tr>
        </thead>

        <tbody>
        <% @product.variants.each do |variant| %>
          <tr>
            <td><%= variant.colour %></td>
            <td><%= variant.price %></td>
            <td>
              <% if variant.user %>
              <%= variant.user.email %>
                <% else %>
              <p style="text-align: center">-</p>
              <% end %>
            </td>
            <td style="text-align: center"><%= variant.product_id %></td>

            <td><%= link_to 'Show', product_variant_path(@product,variant) %></td>
            <td><%= link_to 'Edit', edit_product_variant_path(@product,variant) %></td>
            <td><%= button_to 'Destroy', product_variant_path(@product,variant), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      No Variants Available!!<br>
    <% end %>

<br>

<%= link_to 'New Variant', new_product_variant_path(@product) %> |
<%= link_to 'Back to Products', category_products_path(@product.category.id,@product) %>